tasks:
  - init: install -f & pip install -r requirements.txt
  #attempt to fix init again
  - init: flask init & flask run
    command: flask init & flask run

ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addCheck: true
    addComment: true
